# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 05:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('BrandName', models.CharField(max_length=100, unique=True)),
                ('premium', models.BooleanField(default=False)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
