# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menulist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('cuisin', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=700)),
                ('price', models.IntegerField()),
                ('expires', models.TimeField()),
                ('aval', models.IntegerField()),
                ('menuPic', models.ImageField(upload_to='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerDetails')),
            ],
        ),
    ]
